spring:
  application:
    name: client-service
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server


server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  circuitbreaker:
    enabled: true