spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    waitTimeInMsWhenSyncEmpty: 60000
#    registryFetchIntervalSeconds: 15
#    enabled: true
#    useDnsForFetchingServiceUrls: false
#    shouldUnregisterOnShutdown: true
#    preferSameZoneEureka: true
#    healthcheck:
#      enabled: true
#    instanceInfoReplicationIntervalSeconds: 20
#    leaseExpirationDurationInSeconds: 70